name: Kong CI/CD - Build and Push Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'kong/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build \
            -t ${{ secrets.DOCKER_USERNAME }}/kong:latest \
            -t ${{ secrets.DOCKER_USERNAME }}/kong:${{ github.sha }} \
            ./kong

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/kong:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/kong:${{ github.sha }}

      - name: Update K8s repo (GitOps sync)
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          curl -s https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh | bash
          sudo mv kustomize /usr/local/bin/

          gh auth setup-git
          gh repo clone Prypiatos/platform-infra
          cd platform-infra/k8s/ems-app

          git config user.name "github-actions"
          git config user.email "actions@github.com"

          kustomize edit set image sheharakarunarathna/kong=sheharakarunarathna/kong:${{ github.sha }}

          git add .
          git diff --cached --quiet || git commit -m "Update kong image to ${{ github.sha }}"
          git push
